### ISSUE TITLE
Exception after upgrading to latest release 6.1.0 and upgrading til DNN 9.2.0

### ISSUE THREAD

**Issue by Audun1555** [DNNCommunity/DNN.Reports#37]
Anyone else experienced this?

//A

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1ae36cc1-1866-4fc4-a898-485006efbc23
AssemblyVersion:9.2.0
PortalId:0
UserId:3
TabId:53
RawUrl:/Reports/SomeReport
Referrer:http://SomeServer/DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=65
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Modules.Reports.ReportsController.GetReport(ModuleInfo ModuleInfo) at DotNetNuke.Modules.Reports.ViewReports.Page_Load(Object sender, EventArgs e) at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by EPTamminga** [comment]
Please try to reproduce the error with the debug DLL in the bin folder. This will provide line #'s of the error.
[DNN_Reports_06.01.00_DEBUG_DLL.zip](https://github.com/DNNCommunity/DNN.Reports/files/2080391/DNN_Reports_06.01.00_DEBUG_DLL.zip)

**Comment by Audun1555** [comment]
Hi, sorry but I rolled back before I got the chance to debug.
From the logs it seems like there is a cast of date that fails in the 6.1.0 version.

"Could not cast 07.11.2017 08.44.37 to property CreatedOn of type System.DateTime"

//A

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:cf4ecfa6-bf94-4907-9cd4-b289875e71c2

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:hiuWjMPlbz+ADyW6UIFy5iPlWXo=

Message:Could not cast 07.11.2017 08.44.37 to property CreatedOn of type System.DateTime

StackTrace:

at DotNetNuke.Entities.Modules.Settings.SettingsRepository`1.DeserializeProperty(T settings, PropertyInfo property, ParameterAttributeBase attribute, String propertyValue) at DotNetNuke.Entities.Modules.Settings.SettingsRepository`1.<>c__DisplayClass13_0.b__0(ParameterMapping mapping) at DotNetNuke.Collections.CollectionExtensions.ForEach[TType](IEnumerable`1 source, Action`1 action) at DotNetNuke.Entities.Modules.Settings.SettingsRepository`1.Load(CacheItemArgs args) at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)


InnerMessage:String was not recognized as a valid DateTime.

InnerStackTrace:

at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) at System.Convert.ToDateTime(String value, IFormatProvider provider) at System.String.System.IConvertible.ToDateTime(IFormatProvider provider) at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at DotNetNuke.Entities.Modules.Settings.SettingsRepository`1.DeserializeProperty(T settings, PropertyInfo property, ParameterAttributeBase attribute, String propertyValue)


Source:DotNetNuke

**Comment by dhassall** [comment]
Hi

I had exactly the same problem (I'm new to GitHub). I initially opted for Clone / Download button, which downloads the whole of this project.

However if you choose the Find File button and then put ZIP after DNN Reports/ you then see Installation/DNN_Reports_06.01.00_Install.zip and that's what you need

Dave

**Comment by EPTamminga** [comment]
The new releases are in the release tab in this repository
